version: '3.4'
services:
  secrets-manager-local:
    build:
      context: .
      target: dev
      dockerfile: Dockerfile
    volumes:
      - "./:/workspace"

  tests:
    build:
      context: .
      target: dev
      dockerfile: Dockerfile
    volumes:
      - "./:/workspace"
    command: go test -v ./backend... ./errors/... ./controllers/... -coverprofile cover.out

  secrets-manager:
    build:
      context: .
      target: prod
      dockerfile: Dockerfile
