apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  - secrets-manager.tuenti.io
  resources:
  - secrets
  - secretdefinitions
  verbs:
  - get
  - list
  - watch
  - update
  - patch
  - delete
  - create
