apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: secrets-manager
  namespace: default
rules:
- apiGroups:
  - ""
  - secrets-manager.tuenti.io
  resources:
  - secrets
  - secretdefinitions
  verbs:
  - get
  - list
  - watch
  - update
  - patch
  - delete
  - create
